### PR TITLE
Stop event loop if exception is thrown from test

### LINKED ISSUE #8: Uncaught exception in a test method hangs it
Shoulnd't it abort the loop instead? 

Same happens if we just remove the line `throw new Exception("TEST");`, but I'm not sure whether it's so by design.

```php
class MyAsyncTestCase extends AsyncTestCase
{
    function test()
    {
        Loop::repeat(1000, static function() { echo "alive\n"; });
        throw new Exception("TEST"); // Doesn't abort the loop. This method runs forever.
    }
}
```

### PR DESCRIPTION
**Pull request by trowski**
If the test method throws an exception or the promise returned from the test method fails, the loop is automatically stopped after 1 second and the test is failed, noting that the loop continued to run.

@kelunik Thoughts?

Fixes #8.

### CODE REVIEW

File: src/AsyncTestCase.php [hunk 1]
```diff
@@ -60,6 +60,16 @@ abstract class AsyncTestCase extends PHPUnitTestCase
...
+
+                if ($exception) {
+                    Loop::unreference(Loop::delay(1000, function () use ($exception) {
+                        Loop::stop();
+                        $this->fail(
+                            'An exception was thrown from the test method or promise returned from test method failed),'
+                            . 'but the event loop continued to run; ' . $exception
+                        );
+                    }));
+                }
```
Comment (kelunik) [inline src/AsyncTestCase.php:94]: Shouldn't this immediately fail?

Comment (trowski) [reply src/AsyncTestCase.php:94]: The delay is to differentiate between a test that simply fails (or has an expected exception) vs. a test that hangs after throwing an exception because the loop continues to run.

Comment (bwoebi) [reply src/AsyncTestCase.php:94]: But then a delay(1) should be enough - the loop won't be continued anyway under normal circumstances once it has thrown?

Comment (trowski) [reply src/AsyncTestCase.php:94]: The loop didn't throw, rather the test method threw or the promise returned failed.

1ms is probably too short, but 1000ms is also probably too long. 100ms would probably be more reasonable.

**Comment by prolic** [comment]
@kelunik @trowski I need this here merged and released. I work against this `issue-8` branch for now. Thanks!

File: src/AsyncTestCase.php (hunk 1 above)
Comment (kelunik) [reply src/AsyncTestCase.php:94]: A defer watcher is probably enough?

Comment (trowski) [reply src/AsyncTestCase.php:94]: My reasoning for the delay rather than a defer is that I assumed some libraries such as parallel may have tests that fail the returned promise and then need some time to finish executing, such as shutting down a child process or thread.

After trying `amphp/cluster` with a defer watcher, I found that `WatcherTest::testDoubleStart` was failing because stopping the cluster was taking more than a couple seconds. This was the only test I found failing among several libraries I tried (amp, parallel, http-server, postgres).

I pushed another commit that uses the timeout if set, otherwise uses 1ms.

I'm not sure if we can consider this backward-compatible, as the cluster test passes with 1.2.x. 

This issue may be better handled with documentation on hanging loops. 🤷‍♂

**Comment by prolic** [comment]
I tried this branch and I have a problem with it: Tests fail when an `expected` exception is thrown with something like this: `An exception was thrown from the test method or promise returned from test method failed, but the event loop continued to run; Prooph\EventStore\Exception\StreamDeleted: Stream 'should_fail_appending_with_stream_exists_exp_ver_to_soft_deleted_stream' is deleted`

**Comment by trowski** [comment]
@prolic That's because the loop is continuing to run after the test method throws (or promise fails). In other words, you still have active watchers in the loop after throwing.

File: src/AsyncTestCase.php (hunk 1 above)
Comment (kelunik) [reply src/AsyncTestCase.php:94]: We could also release it as 2.0.

**Comment by trowski** [comment]
> We could also release it as 2.0.

@kelunik Yeah, let's do that. I pushed a new commit that fails any test if the loop continues to run after resolving. If we're going to go with another major, that would be even better I think. A test will explicitly have to allow the loop to continue running after resolving using `AsyncTestCase::setTimeout()`.

In the meantime I'm going to tag a 1.3 that supports PHPUnit 9.

**Comment by enumag** [comment]
@kelunik @trowski Just ran into this problem as well. Took me quite a while to realize there was an exception which was hidden and the timeout exception was shown instead. Can this be merged?
